baseURL = 'https://frocsoft.github.io/HansaemKim/'
languageCode = 'en-us'
title = 'Hansaem Kim'
theme = "hugo-PaperMod-master"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2